### ISSUE TITLE
Issue 1: User can view a list of video games

### ISSUE THREAD

**Issue by Henry-Nichols** [Henry-Nichols/High-Ping#1]
## ⚙️ Feature

> ##### User can sort and view a list of video games

## 📐 Functionality

> ##### The application will serve as a news and review site for video games where users can view latest news on upcoming and released games and users can see their favorite games and leave a review.

## 🖼️ Wireframes

> ##### 

![Screen Shot 2021-05-25 at 5 51 18 PM](https://user-images.githubusercontent.com/73201661/119586578-d82a1700-bd81-11eb-9c86-fd6e2a310478.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] implement endpoint to fetch a list of games using the RAWG API
- [x] implement endpoints for searching games 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create an HTML Structure
- [x] Make use of flexbox in order to create the layout of the application
- [x] Add the necessary styling to match the figma
- [x] Create a component to view list of games
- [x] Update component to use api calls 

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
