### ISSUE TITLE
Issue 3: User Can Write a Review 

### ISSUE THREAD

**Issue by Henry-Nichols** [Henry-Nichols/High-Ping#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

A user will have the ability to click on any game and leave a review.

## 📐 Functionality

A user can use the application to review games that they have played.

## 🖼️ Wireframes

<img width="216" alt="Screen Shot 2021-06-03 at 3 59 09 PM" src="https://user-images.githubusercontent.com/73201661/120722487-a5200b80-c484-11eb-8639-46b2fd95f798.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Create table scheme to hold reviews
- [ ] Create Sql in order to insert new reviews

### ☁️ Server

- [ ] Create endpoints for insert reviews
- [ ] Implement error handling 

### ⚡ Client

- [ ] Update description component to add a form for reviews
- [ ] Add necessary styling in order the match the Figma
- [ ] Make use of flexbox in order to align elements correctly
- [ ] Add star icons in order to give reviews
- [ ] Create a button for submitting the review form

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
